### ISSUE TITLE
Login - UI & Frontend

### ISSUE THREAD

**Issue by kleinchang** [efcsydney/efcsydney-roster#161]
#### User Story
As an admin, I would like to see an interface for me to log in so that I can ensure not everyone has the admin access.

#### Detailed Description
to integrate Firebase SDK using Javascript

#### Subtasks
- [x] Firebase setup @josephj                        
- [x] Login Page @josephj                        
- [x] Error Page @yhua045                        

#### References
None

**Comment by josephj** [comment]
Firebase setup - done!
https://console.firebase.google.com/project/efcsydney-roster/authentication/providers

**Comment by josephj** [comment]
**Acceptance Criteria**
_Login page_
http://demo-roster.efcsydney.org/#/login
- [] Ensure it shows Facebook sign-in popup when you click the login button
- [] Ensure you still see the button after you logged in successfully.
- [] Ensure you are redirected to admin page after you turn on the setting on [Firebase Console](https://console.firebase.google.com/u/0/project/efcsydney-roster/database/efcsydney-roster/data).

_Admin page_
http://demo-roster.efcsydney.org/#/admin
- [] Ensure it redirects to login page when you haven't logged in.
- [] Ensure it shows the Admin table when you logged in.
