### ISSUE TITLE
Password Encryption and Protection

### ISSUE THREAD

**Issue by liam-lai** [efcsydney/efcsydney-roster#163]
#### User Story
As a user,
I would like to encrypt the sensitive information such as passwords
so that it can’t be easily seen or retrieved by an unauthorised viewer

#### Detailed Description
Save sensitive data on AWS and modify code to read those data from AWS. 
Remove sensitive data on Github. 

#### Subtasks

- [x] Subtask 1 Learning AWS Systems Manager Parameter Store. @kleinchang                        
- [x] Subtask 2 Save Data into Parameter Store and retrieve data from code. @kleinchang 
- [x] Subtask 3 Remove sensitive data from github. @kleinchang 

#### References
https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-paramstore.html
