### ISSUE TITLE
API

### ISSUE THREAD

**Issue by yhua045** [efcsydney/efcsydney-roster#171]
#### User Story
As a user
I would like to save the modified event categories to roster system database
so the updated information is made available across the entire roster platform

As a user,
I would like to see the list of event categories from roster system database
so that the information I am getting is always the latest.

#### Detailed Description
The category API provides two endpoints, one returns the list of category information and the other allows the front end application to push the modified information to the back end system and persists into database.

#### Subtasks

- [x] Define Contract @yhua045
- [x] Create endpoint that returns list of categories (GET api/services) @yhua045
- [x] Create endpoint that returns a single category by category ID (GET api/services/{serviceId}) @josephj 
- [x] Create endpoint that accepts a single category item (PUT api/services/{serviceId}) @yhua045
- [x] Data migration - update the CalendarDate table to populate all required dates, update the Service table to populate all required services @yhua045

#### References

*

**Comment by josephj** [comment]
@yhua045 

We probably can put Contract planning as a subtask so that we can plan the API with a holistic view. Do you agree?
