### ISSUE TITLE
Admin > Create Service (New)

### ISSUE THREAD

**Issue by josephj** [efcsydney/efcsydney-roster#208]
#### User Story
As an admin I would like to create a new service so that this system can fulfil all events happening in church  

#### Acceptance Criteria

- [ ] Ensure that the code doesn’t duplicate with the Edit Service (if possible).
- [ ] Ensure you can access it by an URL - https://demo-roster.efcsydney.org/#/admin/new
- [ ] Ensure that the Service Title field is editable and mandatory.
- [ ] Ensure that the Frequency field is mandatory.
- [ ] Ensure that the Frequency has the following options: Everyday, Sunday, Saturday, Friday, Thursday, Wednesday, Tuesday, and Monday
- [ ] Ensure that the “Footnote Label” label changes to “Note Label”
- [ ] Ensure that the “Positions” label changes to “Roles”.
- [ ] Ensure that you can add new roles.
- [ ] Ensure that you can delete an existing role.
- [ ] Ensure that you can change the order of the roles. (optional)
