### ISSUE TITLE
Quarter View (Improvements)

### ISSUE THREAD

**Issue by josephj** [efcsydney/efcsydney-roster#209]
#### User Story
As an admin I would like to see some improvements on the existing Edit Service so that the system get improvements according to the user feedback in the Sprint 3 Review Meeting

#### Acceptance Criteria
- [ ] Ensure the roles (e.g. 大班老師、大班助教) are rendered according to the Service API (e.g. https://demo-roster.efcsydney.org/api/services/4)
  - Currently the roles are generated from the first event data. Thus not all roles are visible on current view.  (e.g. https://demo-roster.efcsydney.org/api/events?category=preschool-junior&from=2018-04-01&to=2018-06-30)
- [ ] Ensure the days are rendered by the Frequency setting
  - Service API has the `frequency` data -  https://demo-roster.efcsydney.org/api/services/4
  - Currently it relies on the pre-populated events data. (e.g. https://demo-roster.efcsydney.org/api/events?category=preschool-junior&from=2018-04-01&to=2018-06-30)
- [ ] Ensure that the Hotjar user feedback icon doesn’t exist anymore.
- [ ] Ensure that it displays the correct service whenever user updates the URL directly. (Daniel - 發現一個 Bug：如果從管理介面 `/#/admin` 直接將網址改為 `/#/chinese` 會跳到英文堂)
- [ ] Ensure that the scrollbars don’t show on the Windows browsers
  - Daniel - Quarter View 的 ScrollBar 永遠都會顯示很醜，是否能有需要的時候才顯示？
  - 把 overflow: scroll 改為 overflow: auto 應該就可以解決

#### References
_List any useful links here._

*
