### ISSUE TITLE
Email (Improvements)

### ISSUE THREAD

**Issue by josephj** [efcsydney/efcsydney-roster#214]
#### User Story
As an admin I would like to see some improvements on existing Email so that it fulfils my expectation

![image_preview (2).png](https://images.zenhubusercontent.com/5a84b2194b5806bc2bc6faf8/eea2d383-3104-4992-9690-95fe8564621e)

#### Acceptance Criteria
- [ ] Ensure all the services have their own caption
- [ ] Ensure the borders are collapsed
- [ ] Ensure that the user doesn’t have a long scrolling
