### ISSUE TITLE
DevOps

### ISSUE THREAD

**Issue by kleinchang** [efcsydney/efcsydney-roster#268]
#### User Story
As a devops,
I would like to containerize our development environment, 
so that developers can have identical working environment as production to work on directly, without having to install all software dependency by themselves.

#### Acceptance Criteria
- [ ] Ensure container of development environment is ready for developer
- [ ] Ensure container integrate seamlessly with Travis CI build server
- [ ] Ensure easy monitoring of container status

#### References

Wireframe? Mockup?
