### ISSUE TITLE
DB Refactor

### ISSUE THREAD

**Issue by liam-lai** [efcsydney/efcsydney-roster#343]
#### User Story
As a developer,
I would like to have understandable db schema and name.
so that have benefit to pick up code.

#### Acceptance Criteria
- [ ] Ensure DB have new table
- [ ] Every Devs Review and agree DB schema
- [ ] API PUT/GET adapt new db schema

#### Migration Process
1. Create new table, migration to new table
2. Deploy Code
