### ISSUE TITLE
Establish End-to-End Test on roster

### ISSUE THREAD

**Issue by trust2065** [efcsydney/efcsydney-roster#354]
#### User Story
As a developer
I can automatically run essential test case when we add new feature or debug.
so we are able to guarantee the system won't fail 

#### Acceptance Criteria
- [ ] Ensure the essential test case are build

- [ ] Ensure each test case can be run without error

- [ ] Ensure each test case can display demand result

- [ ] Ensure each test case can be run automatically 

- [ ] Ensure important test cases can run on full Chrome instead of headless Chrome
