### ISSUE TITLE
Roster Web > Admin > User

### ISSUE THREAD

**Issue by trust2065** [efcsydney/efcsydney-roster#360]
#### User Story
As a user, I would like to send email to some users, and I can manage users with interface,
so we can reduce the manually typing time and avoid typo as well. 

#### Acceptance Criteria
- [ ] CRUD on user

- [ ] Have confirm dialog before delete

- [ ] Create exist users on db

- [ ] Build test

- [ ] Create rule for each field

#### References

Wireframe? Mockup?
