### ISSUE TITLE
Move Production to Heroku

### ISSUE THREAD

**Issue by josephj** [efcsydney/efcsydney-roster#396]
#### User Story
As a **product owner**,
I would like to **have a more stable production environment which doesn't be updated frequently**
so that **the service could possibly suffer less downtime**.

#### Possible Tasks
- [x] Open a shared account 
- [ ] Database (PostgresSQL)
- [ ] CLI Deploy
- [ ] Travis Build
- [ ] Web Server (PM2)
- [ ] Update the DNS Records

**Comment by josephj** [comment]
https://paper.dropbox.com/doc/Migrating-to-Heroku--ALTr01rwTFzPiPKz8TTIVEojAg-CmWHE6iEQuiEGX5XGJIqE
